import { Test, TestingModule } from '@nestjs/testing';
import { Day3Service } from './day-3.service';

describe('Day3Service', () => {
  let service: Day3Service;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [Day3Service],
    }).compile();

    service = module.get<Day3Service>(Day3Service);
  });

  const puzzleOneTestInput = 'vJrwpWtwJgWrhcsFMMfFFhFp\n' +
      'jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n' +
      'PmmdzqPrVvPwwTWBwg\n' +
      'wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n' +
      'ttgJtRGJQctTZtZT\n' +
      'CrZsJsPPZsGzwwsLwLmpwMDw';

  const puzzleTwoTestInput = 'vJrwpWtwJgWrhcsFMMfFFhFp\n' +
      'jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL\n' +
      'PmmdzqPrVvPwwTWBwg\n'+
      'wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn\n' +
      'ttgJtRGJQctTZtZT\n' +
      'CrZsJsPPZsGzwwsLwLmpwMDw';

  const puzzleOneRealInput = 'ZTmtZvZLTFNLMQMNRvZncdcHwcScJvcdHnVfwV\n' +
      'zqjqrzqjCqrjtqWhqChqrznhcfdfVnVSVgcffcgJcSgd\n' +
      'rtDGpzjjqjlrGsWqBWFRsbTPFQMTbRNRFmbs\n' +
      'FFlnlnVlmQqcBVhBRrSrGSwVdRJbztSt\n' +
      'NPPNsffWfNztRZSJNG\n' +
      'WpgpTTHDpgTDDpMLPGgMHslmBmmHcBQnFmcqhmnjlqQm\n' +
      'VlVNLlPQhtnDRPnP\n' +
      'QgqTffzZqgvgzWmqqZmGcDthtRFvnnFnhJtJJDDt\n' +
      'WGTBzSqBQTQmZBWHswpNbswLbSNCNl\n' +
      'PFzFQDdLjMzzQDhnDNmwZmqwRsmRRmMVNM\n' +
      'GtSbbtlttvvtBvtHBmqqNqVVwsVgCmRw\n' +
      'brlvctHfrlrqvGvcTpjDdFnLDhdfjLhQpn\n' +
      'fTqzgFrcmzTrTNgMzFzTrgtbMtVMVPSLVbvSStRttPVV\n' +
      'lsHnlQhplQpsHhlDJsswNwZPZZVNwvnSZSVvVS\n' +
      'BJpsGWhWQQHdGHlpWpfgrmqgNBmTTBqzTrzr\n' +
      'PLPPrDNHDBnrWNBmjDmjbqqgzjgjQC\n' +
      'GJpFwpvFFsJpwvwwGwJZJRptzdQSSZTmCjTQmTSQjjZSggQQ\n' +
      'ffwGGtJGCfLcNMNNfNLW\n' +
      'nlTzllGwlQHHGMSrrhQLcvbcghgcvL\n' +
      'fFNpttBRFFRNtJJnfNWmqbhhZrZrcjgpvLrvrvcvbr\n' +
      'JBftFFsVRWtNWRsmWtRfftGHGPDDCnTDHSCwzwVnwGSw\n' +
      'LsrZLbLmPSTZtPcc\n' +
      'zpnpljpdwhRpfNLlPWPtTPcnMWPcctTV\n' +
      'qlhNNjldqdpgqdfhjpphdsgmmrDBBJJQgHrmDHLQJb\n' +
      'ndDrsBbpqspHCjzVBCHjMj\n' +
      'LWFcQFQtVVdcCMHC\n' +
      'RLthwTWLTSLwTllRLLlLNlPpPGfrGnqDdGqsZqsZsZhb\n' +
      'jHnJLJrcBbrRHJpnLBBjdHbjfgvGwstwWwdsWWshfhFzFfhv\n' +
      'PZDQMNTMQwtgvGTGhf\n' +
      'lqlPPQZQVSQCPSCPDmLppjqRqHngLHjRgLnL\n' +
      'MfQrhdzNMfMPsNNmPmqPLCLCVLBnbP\n' +
      'WVtcVvJJVjvFZZmgGjnjLBjmnnHB\n' +
      'FFtcZRpWJcSDTwlVMhMDwrrDzM\n' +
      'bSMbrQGZwwqbrbGMdTQGMwQdfFBLDLHLHssDgsHHBJDsFfwL\n' +
      'lpPPCccvVPvccPzcWLDJFJBsBzJJHsqHjg\n' +
      'tnqlPlVlNvNZZSSrGGZb\n' +
      'NlBBBBBwmwcMgLwLVVLLLscHdnMDdbHJCbdvJbPdDDJHvn\n' +
      'ZRWQWSfGhtSjqZhffZhhRjtdvPFHvCJbFdCFFDdHJdPb\n' +
      'fpqGhQWWZRhfqRSqrpGllLcVLmscgrLwBmgCzN\n' +
      'wHHHwDNCzZwzZfpzwsswzfzvnvnMDMgMhMGGFGRVdMnvcF\n' +
      'mLtttqTPBtSJTSBQWlmcMvVdclnvhFggdGhRdn\n' +
      'QBLPSLQQWmLtTBtBSjZfsbwbHzpjGzHfpzzw\n' +
      'zDPBqBPqwzzsqlTzzPzqjttNbCPJVtPCbrvjvCZP\n' +
      'MFhMhGfFfGpWWpHhFfRpHjVNbDbJjVMjrVvVNtMtbt\n' +
      'gfRSmpggSFRgfGRphFGgfgBSBTqzSsdlTLqdsnsDBqLw\n' +
      'QTTdWZZZTrhCZrjhVt\n' +
      'SBJJNRRvvRpwwspNSpTPjCMVhhtCjGThjBjB\n' +
      'fJJpvRRwNRSwvzRzRvzSgSRNqFTFDbFmqncQTbdFfnbDQnLW\n' +
      'wSjwwjWhbhhjWjdqSVpqSndvMdmM\n' +
      'NTvPBrZgPPHDFrFHGvZHRBqVBpCQVRRdmpRppdqM\n' +
      'TgDHZPsNTWbbwsjtvw\n' +
      'HVRPRwJVppQNpGmvMvmqqq\n' +
      'WcttbWsWsdDdbFDSSWclZGvFLMvfvjfzNvLGzLmfqv\n' +
      'tglcmSldWlBQBThRQBhg\n' +
      'LDGGfPFLGsfFnGLfMzfJVccNzmcmwm\n' +
      'qggSRgtjgCRtdtNZCJMCcZwTZVcm\n' +
      'RBbHbbRRnLBDDrvN\n' +
      'pThhMtMtTsWspWTnGjpsVHPdjdjvHdgVvLDVVSjd\n' +
      'JQNrrwCFrSRLRVLnSN\n' +
      'JQcJFCfcnfQmrbblQqlthGqzpZpGTBMWTMqtst\n' +
      'DzVmzDDgsNdHHLGJhJppPPllqSgbql\n' +
      'jrBWjcQMCRchPShwSblpbW\n' +
      'ZjRrSCtnnrtBQTcrSZmGtGFFNDHmHVVmVtzz\n' +
      'GSbGbrTGRRScMlVFjfbqqjdF\n' +
      'tvDmZhtNtHDttBhCmHDJHNwlpjslMwfflvpqldsFpMlf\n' +
      'HdBhLDhJDLWWLDCSQGcrQPGccLTGcQ\n' +
      'tNzrCdJBrrtQdtgQdlQQtrnMZhMTqzHqqTFZZFqTHFMV\n' +
      'bwbsRDvfwfsfcfSFqMmqDqFVNMNVVH\n' +
      'PRvfbSjNvPWPlLllLJ\n' +
      'MjMRRNRMjZtGVGpBCMMCDV\n' +
      'vwfhFzhvcJQQwJlQSddzQwFWGqcDpCDqBqDTcGZTTVTCWG\n' +
      'dvFJzrfZJhddLNLPHsrtRbPr\n' +
      'BmbsFNBhszGgGtGl\n' +
      'MSHVwdSwZflGlcqqpM\n' +
      'QvwZCnnnSvZdCSWrNmDlPPBPDhPmjW\n' +
      'MDwpRzRwMzMsdVSjdMWWMQdW\n' +
      'gmlftnDtHnHHVWSWBjWjWgvW\n' +
      'HbtrhbbGRNDpbCDz\n' +
      'cjVGqQqVqBFhDtvB\n' +
      'ZnTTfTffZZmDhBtJZG\n' +
      'fNzbpzlHTlgHNzlRTlRNbHrWwrCwWSSdQddNjwVcjGSd\n' +
      'WWrPMhwhnjpSLCpDlSSW\n' +
      'sNGBGdmTbZNGsmbstNLZGZDBRSlqSRCfRSCqRRDDqCqp\n' +
      'NvvcGtsLdTNZmLTmdJPcnnMFjFMcrVJhMF\n' +
      'wMRQMSQZHznRsqRbWp\n' +
      'ddgDDhfDrrDdjthHmdHrzpbVCVWFpfVqCWpWqpFs\n' +
      'hdvNdHtjMLJZvJwM\n' +
      'nWzZtWzHzZWgQHMNLDMDfDBfQbdD\n' +
      'MCPmRGGhqdmNjbDN\n' +
      'FRPlMlRChCvFggWZsHsZHn\n' +
      'ZGhhjdgwgcZHsPnRnSnbWscn\n' +
      'tltlfMQQQftDFJpMQJsWJWJsnWBnRSBbrBWP\n' +
      'lfLDpQMFMNfLjGjPPgZzwh\n' +
      'HcmvWcqnHLLPDzPPHM\n' +
      'MGGSfdJRdCglfrLjrjrLzLPzlF\n' +
      'CsgRgfwgdCwhsssJBBwvcnQnQNMvQtQm\n' +
      'nrVbwgnSTSgSnrZpjpWWqmWNHlqqpV\n' +
      'BcBPhSdsDlHNtNlJNP\n' +
      'RLFCQLQRRsBDDcRdGDddhCRDfwzvSCnzrbfrMfMgznwwfbZv\n' +
      'HJLzLNwBNzNJLzBJztRGzQVnDgwsjbgwssZwnDZbDQ\n' +
      'PhvlSvvPfMRlDbDsggbSjQSg\n' +
      'mFfhMlMrfchvPPpFTPvMvPzLBHWRHJNtzJGzzHpzBtCC\n' +
      'FLsgSLzLswdFgLBbWZnJDWHcmZnnBjHM\n' +
      'rpbrrqfqpvCbqqQQvvpClblRDHmjmmjJJZZnWMJmmJmmcRMc\n' +
      'qTppQvCfhzSVVTzbdL\n' +
      'ThTJtlqfDrDtffwqRCFCCnLwdnmpzRdF\n' +
      'WPQSSFsGMgQZWvFQgZgZQcCdmmzLMLCpNzCCddmLzdzm\n' +
      'cvVPGPQQGsZsgGPjVFccbHhThJHhDqfhDDjHqDrr\n' +
      'CgnCCnPMnMtGHDbMFQ\n' +
      'zLpwpRTwwRwhRchHwmqmGvvGbqmTmNQqvq\n' +
      'sHdhzlwrRVrdLzRrprrfjgfjVBnBCfSBZZgPfJ\n' +
      'SPMdWwWPrZwdrrWrSPLFDfgbQDfwDFfFglDQ\n' +
      'qLGBtGLpjzqmvQbvvpDvfFpR\n' +
      'jhLqqHBLGjtLqSZCssSTZZMshP\n' +
      'MhJCpPDpRRFRzQQNNqbcZjNZmVhjNm\n' +
      'LLSlLnGDmNqLbNjb\n' +
      'sfBngrBSTTSnSGHlTsHBGsBpFFdRdQPDCFPWRMzzdQWM\n' +
      'ZQtmgtWfPcgPgcsb\n' +
      'pvMhFThpHVTvPbcFcFJLJDsd\n' +
      'MTVHchVVHjHHTcpjMVBjjnQnGqQZnlqBmrWQQBffQQ\n' +
      'HfcRNJpJfhCmpGSqqGNjsjBnQl\n' +
      'tTdPwwtLTrrTVPSnQsbGPsnnlFllFQ\n' +
      'VvvTSTwWMrSZVwwrrmRmczJchHcHCZhRzD\n' +
      'wfRwhmLRnvrHqHhV\n' +
      'bJlBHlWlHMBPJzDlzMMJJSBlFnrGVrqspGGvpVGPVpGsVqvp\n' +
      'DWdStDMztCCHgZCtmZ\n' +
      'MHdsznVDDfcjcjDcdDjmMSCQwQpCpFCvqSZQqFzQpQ\n' +
      'lhJnLJJnTNrWTRqvqqPrFwZvwqQp\n' +
      'NghhtJBtnWLRTNjmcMDtjdsMfGDH\n' +
      'jgsvPffVmHfDqPSrNwnQwnwNhSvw\n' +
      'PZbGbCdcGdRCGtntQLQQLLwtpLNw\n' +
      'RbcPFBRFcdZBBJDBmTHjsD\n' +
      'dTTFJdzhmmmQpzVz\n' +
      'jtNLcctGGjtfrnVMsNQNQVVWnv\n' +
      'GcrcrfLtDggLftDFhZFdJFHJBVFBgZ\n' +
      'TTbqTgqCqZCrwmhQnnmrgh\n' +
      'MhpfsMLhfmrznLrQrF\n' +
      'RsStRMtjpHMfDtWsWsNDppsqlZqBlhNlbcNdTPClPqcvBP\n' +
      'lRhZPgnpRGZlSrmsLSvSzLVl\n' +
      'wwHdHCfDQCJHdwdDMdHCcDsLmNVvzVsWrcVNcVzLbrLz\n' +
      'dMCCwCtJdwDQJMtjhnvhpPhRZBhR\n' +
      'pBqMZfDffmBnvnNmPt\n' +
      'rhwLHCChrLPCMNWMCNmW\n' +
      'GSMVRSVwHLMRJDQJTZlJZR\n' +
      'sfstzPGRRBSngMfQLNNqgWLQLZZNgq\n' +
      'scVDjjjCDTVhHlDhHdvvjwjHrZmWQmJmrJJWqNqLJbrcQqZq\n' +
      'VvHlVHldTjvhpVplhVThhwjlPFSzPfGzpGBnsRffRRBPPGGF\n' +
      'WNFNfnWTSLSJTnWShTvVZCnvrdPrZvddVCrt\n' +
      'QwsMjppcpHCPdHsvPZ\n' +
      'lcwMGgpcGbzQpMgQwbDjDQZSJTRfShffWNJSSNFFbhSb\n' +
      'JDNgTgqDTggQbQGbZDWbJmVJrPVfPjlPfPwlljJC\n' +
      'FZzHFSznZZtptHzcSmCVrwfPVcwwVrCcdm\n' +
      'nMSStvnZFSHpLLtBtMzHnMWQvNhgDgGNRGNhgqRWTgqg\n' +
      'SJcrhvbBLBLrDpllvnwHQRnllHnQ\n' +
      'ffsjfMMZfVdCCgCfgTzmzslRtwFwFtTnqqHTJRQnqRqq\n' +
      'CVPgmdggVjCJSrhrbrPrrSLW\n' +
      'LPtcLtgddLMRRCMRpTBRrZnppvvGRvBw\n' +
      'WNNJjDjqSjJSqWqzNqzlSlBTGGFvrppSrwTFpn\n' +
      'qbNDWNNHbJqVtctwVmsfLCLP\n' +
      'FvSSLMqgvVSQjQfgwpwWpj\n' +
      'BthszRPRRNbNtzmHRbHNRNPfwJGcsswWQpffJpfsJcQFwJ\n' +
      'bBtzPmRrbBRHtNCzPhqdCLFMLSSvdnvCTnML\n' +
      'VPHWJPDjVLDDjDSFDJhgdnNGdbblzTzNjlnNbl\n' +
      'ZprsRZMQwwmGZsvtQZgTfggqnbfdTzrbqlTd\n' +
      'GZMtsscmsRZswwBQHBhDDJJPPCPWSWCJ\n' +
      'mNDNNmmVMSVgGgGGqsqGLhQqsLGhLq\n' +
      'nZBTZpJPhCpnnrsqbbcfczJfFccz\n' +
      'HpBZZRPRHjnPPjrHnRtCZnBdShDVlMDNDgVmtmDdVDWSdN\n' +
      'tBftztmztGBBCBSGHBmhvHHcchbshhThpbLJHJ\n' +
      'wwzMrrMnQdldVdMvJTcLNnphphbLJv\n' +
      'ZzwPVrWQlwrdStGGCWqDSSGW\n' +
      'QwfrQPvhwPfzQrvWWpQpvVGGTDGsjbgNNcbfsGTsDFgG\n' +
      'CtddSdZMRRdnJhRnHtZtlRMbGGDjDgggjNTZDNgTGFgGjc\n' +
      'mdmdCnHhVWmLmwwL\n' +
      'zLcWSWFcPJLWrWLSZrJLjVjHtjVsrdtstHdtVQgg\n' +
      'nChlwwnmhlCNqhhjHMgDjVVdwMjdtd\n' +
      'CNnBmNNThhhdhCdlBGGlGvNpcJbJLSbcZzcFJzpJTWPbzc\n' +
      'LdPZTPVpLCVTtCNsNsfFnlDC\n' +
      'SMwqcqcWQMbMhWQzBnsNfsFwrnnNNlrs\n' +
      'WMMWhvQRNNNjvLgZ\n' +
      'DWFGzrtfsZHZZMLt\n' +
      'pNwNzNCNTpppmnvNMTLVjHLBLLjMRTLH\n' +
      'PPdlPmJJNNClDdcdDDfWhzrW\n' +
      'nSJVSHQQnwLThnhrML\n' +
      'ddsjfRdGZjmGjRTwwTZhwrMwWwtb\n' +
      'qCdfRdMmgssPfjsdjdPspBzQpScSSCBpzNBQzcQz\n' +
      'fJnmRMJrlrmRmTRmbqssWVdqNVQdswdNNb\n' +
      'GZggFHGhHHgHSFvtHPPPsfwgwNsVqjqNpNjNNssN\n' +
      'PPSPDDBPBmBMlLfmLr\n' +
      'BdqdCBqqCVPVTZBrlJcTcTJTcfcbwwmcgv\n' +
      'WjGGLzLMhpWQmRGhpHfbhcDhHHHhgcsbJD\n' +
      'tQzSGjWRzWBntntrZmVB\n' +
      'clfLQLgfzfTLDMwNrNrrNDGCGG\n' +
      'tmbpFtBvvmvdQQdFQwMJCG\n' +
      'SnbtnqnSbnQQsBqzgLgVsLZTLTPfVg\n' +
      'QnQBQQBVzqqzpmfgBpnqSDFPjhhWsFVhlsFFsDstFs\n' +
      'MGGrTHcvRTTrrrCDpjvWtFPlFlsvjp\n' +
      'bZbpTpJJBBQmBmJf\n' +
      'dNVgDdVtPcNPhgTLPLpTPlnTHHRn\n' +
      'WrvjvwjWwfwWjGJsrwBjQJjTQLbnSTTmpTRQSTClHTbLmn\n' +
      'JqWWGvBJBwGJfJJGvwqZZddFtDFhgDqZhHNM\n' +
      'VwJcNgbfvfJbfcmGLZfPhZLfZGTDhP\n' +
      'CnnrlBlprsBnzQFntnZLqDhZZqThWGtWWSPL\n' +
      'FllFdCjzlsCzjJNJGGJwHHVg\n' +
      'fTbVBmNJCJRVbTmbfJFHsDjQHDHQjnQRsvDn\n' +
      'cLWcrGtttddMPhrPhPtPrtzsnSQQBvHjFpFSpDHsMjnvjD\n' +
      'PrPgPdhGWLrrqgdqcVCffbNblBwfVmwqwC\n' +
      'gmBfbmlbBDqrdfrDcJ\n' +
      'PwVWrQphQWWhQsJFcMPqzDdcJq\n' +
      'QWCSSHpSQWCttQpCRCHNSlZBtrmBZTjvGgZjmBZjBn\n' +
      'JrnhMPvtVtPVHJGrBrQwTmQmRGGB\n' +
      'pSSZCFClCbbSLbljZlSlFFszzBwcZNwTzQNDmBwGTBNTBz\n' +
      'ldsCCjpFjCqdLgsFjpsLFQgtnfqtJvnMtnvhWnHHMnnVWV\n' +
      'hzNHzHjWNzwHjjhprpGvGgvGvvpv\n' +
      'PLBVVRPDLdrgCdMrdrdC\n' +
      'FmBTqTmLPrsFqTBDcTTVtNNJztqWQNQtWWtJqNNz\n' +
      'fFffFvFBgHQWHdvfGglBWbqbPSSbSwVntPhZwwbS\n' +
      'jJCMzNMCjNCLNMjjphPSPqhbqnwPZLSqZh\n' +
      'rNpJJDzpcNMzzdBnGcQTccBvgv\n' +
      'FRFMwsrzVtwstgbCHHJJPgNb\n' +
      'hfZGhZDnnTTHTCCNzJjH\n' +
      'hppDvznmZphZQVFQwFVWlRqFls\n' +
      'jrjrgdHdFBZsBlcCGghWNgpgbCCp\n' +
      'QwJJqQQMLwPTwLMMwzvzwwzhCWbvcNcCChWpchWbNGfFff\n' +
      'qqFQJTmwJSPjZsrlnBjdHm\n' +
      'QfffRppWfHpQSrWVpSGmGMMccSjBjmmGmc\n' +
      'qdzLvbwzwdsWwnFdBBcBhMjMDvBBcBhc\n' +
      'bPdZPqddqzFsZVRptZZQHVWNpN\n' +
      'BzBQQHNjTSzzJDDFZFgJDJ\n' +
      'qLvCnLpfCpqCnLJhntRglFncDrGrllmZFZlDrc\n' +
      'JpqvfhRhLddfpbbtsdJWjHSwHHTNSQNPTVHQTb\n' +
      'qVQCCVlQZWgHZMqgqWlrtScFwrmtmcJqSSsSJS\n' +
      'MzdnddpNLzhRpzbzNPPBbPScjcnmrwSFjSjSJFtrwjcF\n' +
      'ddTzRMPLdLbvhBRdLWGQClVVCWQZQDTGGf\n' +
      'DHHTsldDNdPnVDCRDCNHllHwcMpprSMpRmphhRWhrhmzSS\n' +
      'qJLBqQLvJLQgftgPjJrhrMMWSmWMmMrrSqrc\n' +
      'FjfFftgLBjJPBLQZGvvZtNClnTTNGCdHTbCCNsnslH\n' +
      'jHHNsNqhjsShsshdRRCDMfMbCWHBrGGC\n' +
      'TJQFmnpgmTpBDCgCMCDZCGDC\n' +
      'FwpQzwQTmVvwTJmFJzTcQSdhBNztNPNjSlqLhBNhSh\n' +
      'vBCfSDcRMfRcRHSRRZZtPwrWWNtdSmrNVGSdwm\n' +
      'gbLnTzqTbjhGqFzgWrtttQtrPQTtNPmP\n' +
      'zbhjzglgzzlBGcsflsCl\n' +
      'jNHDNNHjVGVDNQFDTQSFZzDQTd\n' +
      'vvLwhbnpvPPgClwnfFTmTZQgffFFtTfc\n' +
      'LrhrLvwrnJvhCHVVRZNMjsRJVB\n' +
      'ShfcBWfvdhhJBBVwCJjHTRNwRVNC\n' +
      'qQzlDqMDDDslPqGVLTNZVpPwTRZZpV\n' +
      'bgbDbsqzsDTcfrgFFdgg\n' +
      'vlRHvvHwvMMMTTlvjmRtBjSJmSnDnpdrpSSrJJnDQrLp\n' +
      'cPfCgZZzNzzcGhNszcTPNZLrnVSJpJhDrrhSSQSpDDQn\n' +
      'FbTgbGcgNgcFbPFHMqvjjRtjRWvFvt\n' +
      'fZTnqfFFDNglcjdjZcfLGQJBwrGGQwbGQTBBJz\n' +
      'VhvfvsPpWRChmphvRGBbBLGhSbLrBQBSwb\n' +
      'pCsCsHvsstPsfRMMMtmDqFjngdFZqDHFnNFFjl\n' +
      'PVVwffMlfGWMDDSwfDwVpRpsZRjBHgpSsjJSpBSp\n' +
      'TdnFbqTFdmbjctcqcbRBZtJJZgsBzBBzvgHJ\n' +
      'bNmbcqnnbNFLChCVCfjDfWlMjVDPCr\n' +
      'JBLLjBQccLLJhcBDDlSrdFDsVhrVsR\n' +
      'HgNWCgqWGbvCRRZvGWvZmszsSlrWdSdFrWzSldDF\n' +
      'qvGCZGHggRNHvGTgvLnBjpjjPJwTPjLcJj\n' +
      'GCGwQrwBZMZdGVdLzbqbbp\n' +
      'TRfTTCtgcDmhtDmsTDVSbvpLdNpzNVRqVdVL\n' +
      'CfDJjscgTcsjfhtFZljPZWZMWPlZjQ\n' +
      'WsrjjfRfjjZjwjWjBpDpVpVhMBsMMSBT\n' +
      'JgmqHnCHHPCCtCJgSZMgZppDTgzvzZMz\n' +
      'HCGCGqqqCtmnHnqLFHWjlFrWRRbfjZccNWrR\n' +
      'BJBfSfPLPvdhvrbbvpDsHgDTzgpdzgZpgN\n' +
      'cVcmRnCWCqGngHpZsZsTsqNN\n' +
      'jmGCVwWjjnWFMjGwcwmrLJbBJPbLSrPPTbFBTr\n' +
      'SPZmmtlmqjZlZMwhlrtggqGGcCLCpfGLgqdCqF\n' +
      'FBBVDVTVDJfgcddLCDdp\n' +
      'zzVHvVNTbWJJTTRbVWBFJbWHmwmSPlMjPSShjlhMhhrrml\n' +
      'GJZJZTsnhsDJtVZdtsZJZrBCQpLjQgBnrQgjCjQQQj\n' +
      'RPSfqcRShHbFcPSfBqLLprBCwrQQQCqg\n' +
      'zPzPRHbFPcRRRHPclMhSfvfZsJZVTTZsJNVMGWGVdGTWWD\n' +
      'lCZrCLWCwVllGzWPPBMTFpsbGdsTpsbNMgFb\n' +
      'RDjtjHcHjcHctDRtjnhtnHTgMqTMqhTbdbdZbgFqZdMN\n' +
      'vfDmvfjtmvtcHmjZfSRZHQzBLrVLCJLJLfJBPzVJlwPw\n' +
      'JMTHVZMWNSCwCwMS\n' +
      'nsddQbDCnQQdDBPdCQCSvwpDvwffhfSvpmppvp\n' +
      'BssqBFtqRHgTqVRC\n' +
      'cWTTthtrgrzpCdCddtpz\n' +
      'SSSLNJLGLSLfCJfJFQCJzQ\n' +
      'swMPMZVMMSlMSZMqVSSHznzcqgzWTHgTnhbnrr\n' +
      'RJjjgMjWShPqchtbVBPV\n' +
      'DDddwCnZMHLLvDnfLrvvbVbbBtpwVBVPwtVpbcbb\n' +
      'zrvnvLrlZCHrfZZLffHZHHTsTmsQgFQSFTMjjQlFTRmR\n' +
      'zhTTMLRVTzLbVqwVRJgDQQsSCgCDNgsZCpqp\n' +
      'rrmrBmmWrWnHjWnGWrnGnhDHSQgNSpQsCgSNgtNtDDHZ\n' +
      'fBrGPGmGPBcTMfLhJVTc\n' +
      'TbTCjTBSbCncHsDZDZPhZbzv\n' +
      'rMwplFdlWWJMJzhhpGtHtvHSSP\n' +
      'fMMfwWdWrNfJNdlVgMcTLTmLffjTqnLScCjL\n' +
      'SwhTllwJDwqqBWLBbNtfhjBB\n' +
      'mvllZMmRMZGFZRfctLWtWttzfNLR\n' +
      'MGvHMCGpVnFGlgvVFFnpnGmmsHrDJJdSsqPqJSqDJJdTTDqD\n' +
      'QTTcqJZJhHSpShhFpFzjDDwwsFzpdg\n' +
      'NBMnBvmBPvwrqvgvvqgD\n' +
      'bNNGmWmbbClQTQRqchhQbf';

  const puzzleTwoRealInput = 'ZTmtZvZLTFNLMQMNRvZncdcHwcScJvcdHnVfwV\n' +
      'zqjqrzqjCqrjtqWhqChqrznhcfdfVnVSVgcffcgJcSgd\n' +
      'rtDGpzjjqjlrGsWqBWFRsbTPFQMTbRNRFmbs\n' +
      'FFlnlnVlmQqcBVhBRrSrGSwVdRJbztSt\n' +
      'NPPNsffWfNztRZSJNG\n' +
      'WpgpTTHDpgTDDpMLPGgMHslmBmmHcBQnFmcqhmnjlqQm\n' +
      'VlVNLlPQhtnDRPnP\n' +
      'QgqTffzZqgvgzWmqqZmGcDthtRFvnnFnhJtJJDDt\n' +
      'WGTBzSqBQTQmZBWHswpNbswLbSNCNl\n' +
      'PFzFQDdLjMzzQDhnDNmwZmqwRsmRRmMVNM\n' +
      'GtSbbtlttvvtBvtHBmqqNqVVwsVgCmRw\n' +
      'brlvctHfrlrqvGvcTpjDdFnLDhdfjLhQpn\n' +
      'fTqzgFrcmzTrTNgMzFzTrgtbMtVMVPSLVbvSStRttPVV\n' +
      'lsHnlQhplQpsHhlDJsswNwZPZZVNwvnSZSVvVS\n' +
      'BJpsGWhWQQHdGHlpWpfgrmqgNBmTTBqzTrzr\n' +
      'PLPPrDNHDBnrWNBmjDmjbqqgzjgjQC\n' +
      'GJpFwpvFFsJpwvwwGwJZJRptzdQSSZTmCjTQmTSQjjZSggQQ\n' +
      'ffwGGtJGCfLcNMNNfNLW\n' +
      'nlTzllGwlQHHGMSrrhQLcvbcghgcvL\n' +
      'fFNpttBRFFRNtJJnfNWmqbhhZrZrcjgpvLrvrvcvbr\n' +
      'JBftFFsVRWtNWRsmWtRfftGHGPDDCnTDHSCwzwVnwGSw\n' +
      'LsrZLbLmPSTZtPcc\n' +
      'zpnpljpdwhRpfNLlPWPtTPcnMWPcctTV\n' +
      'qlhNNjldqdpgqdfhjpphdsgmmrDBBJJQgHrmDHLQJb\n' +
      'ndDrsBbpqspHCjzVBCHjMj\n' +
      'LWFcQFQtVVdcCMHC\n' +
      'RLthwTWLTSLwTllRLLlLNlPpPGfrGnqDdGqsZqsZsZhb\n' +
      'jHnJLJrcBbrRHJpnLBBjdHbjfgvGwstwWwdsWWshfhFzFfhv\n' +
      'PZDQMNTMQwtgvGTGhf\n' +
      'lqlPPQZQVSQCPSCPDmLppjqRqHngLHjRgLnL\n' +
      'MfQrhdzNMfMPsNNmPmqPLCLCVLBnbP\n' +
      'WVtcVvJJVjvFZZmgGjnjLBjmnnHB\n' +
      'FFtcZRpWJcSDTwlVMhMDwrrDzM\n' +
      'bSMbrQGZwwqbrbGMdTQGMwQdfFBLDLHLHssDgsHHBJDsFfwL\n' +
      'lpPPCccvVPvccPzcWLDJFJBsBzJJHsqHjg\n' +
      'tnqlPlVlNvNZZSSrGGZb\n' +
      'NlBBBBBwmwcMgLwLVVLLLscHdnMDdbHJCbdvJbPdDDJHvn\n' +
      'ZRWQWSfGhtSjqZhffZhhRjtdvPFHvCJbFdCFFDdHJdPb\n' +
      'fpqGhQWWZRhfqRSqrpGllLcVLmscgrLwBmgCzN\n' +
      'wHHHwDNCzZwzZfpzwsswzfzvnvnMDMgMhMGGFGRVdMnvcF\n' +
      'mLtttqTPBtSJTSBQWlmcMvVdclnvhFggdGhRdn\n' +
      'QBLPSLQQWmLtTBtBSjZfsbwbHzpjGzHfpzzw\n' +
      'zDPBqBPqwzzsqlTzzPzqjttNbCPJVtPCbrvjvCZP\n' +
      'MFhMhGfFfGpWWpHhFfRpHjVNbDbJjVMjrVvVNtMtbt\n' +
      'gfRSmpggSFRgfGRphFGgfgBSBTqzSsdlTLqdsnsDBqLw\n' +
      'QTTdWZZZTrhCZrjhVt\n' +
      'SBJJNRRvvRpwwspNSpTPjCMVhhtCjGThjBjB\n' +
      'fJJpvRRwNRSwvzRzRvzSgSRNqFTFDbFmqncQTbdFfnbDQnLW\n' +
      'wSjwwjWhbhhjWjdqSVpqSndvMdmM\n' +
      'NTvPBrZgPPHDFrFHGvZHRBqVBpCQVRRdmpRppdqM\n' +
      'TgDHZPsNTWbbwsjtvw\n' +
      'HVRPRwJVppQNpGmvMvmqqq\n' +
      'WcttbWsWsdDdbFDSSWclZGvFLMvfvjfzNvLGzLmfqv\n' +
      'tglcmSldWlBQBThRQBhg\n' +
      'LDGGfPFLGsfFnGLfMzfJVccNzmcmwm\n' +
      'qggSRgtjgCRtdtNZCJMCcZwTZVcm\n' +
      'RBbHbbRRnLBDDrvN\n' +
      'pThhMtMtTsWspWTnGjpsVHPdjdjvHdgVvLDVVSjd\n' +
      'JQNrrwCFrSRLRVLnSN\n' +
      'JQcJFCfcnfQmrbblQqlthGqzpZpGTBMWTMqtst\n' +
      'DzVmzDDgsNdHHLGJhJppPPllqSgbql\n' +
      'jrBWjcQMCRchPShwSblpbW\n' +
      'ZjRrSCtnnrtBQTcrSZmGtGFFNDHmHVVmVtzz\n' +
      'GSbGbrTGRRScMlVFjfbqqjdF\n' +
      'tvDmZhtNtHDttBhCmHDJHNwlpjslMwfflvpqldsFpMlf\n' +
      'HdBhLDhJDLWWLDCSQGcrQPGccLTGcQ\n' +
      'tNzrCdJBrrtQdtgQdlQQtrnMZhMTqzHqqTFZZFqTHFMV\n' +
      'bwbsRDvfwfsfcfSFqMmqDqFVNMNVVH\n' +
      'PRvfbSjNvPWPlLllLJ\n' +
      'MjMRRNRMjZtGVGpBCMMCDV\n' +
      'vwfhFzhvcJQQwJlQSddzQwFWGqcDpCDqBqDTcGZTTVTCWG\n' +
      'dvFJzrfZJhddLNLPHsrtRbPr\n' +
      'BmbsFNBhszGgGtGl\n' +
      'MSHVwdSwZflGlcqqpM\n' +
      'QvwZCnnnSvZdCSWrNmDlPPBPDhPmjW\n' +
      'MDwpRzRwMzMsdVSjdMWWMQdW\n' +
      'gmlftnDtHnHHVWSWBjWjWgvW\n' +
      'HbtrhbbGRNDpbCDz\n' +
      'cjVGqQqVqBFhDtvB\n' +
      'ZnTTfTffZZmDhBtJZG\n' +
      'fNzbpzlHTlgHNzlRTlRNbHrWwrCwWSSdQddNjwVcjGSd\n' +
      'WWrPMhwhnjpSLCpDlSSW\n' +
      'sNGBGdmTbZNGsmbstNLZGZDBRSlqSRCfRSCqRRDDqCqp\n' +
      'NvvcGtsLdTNZmLTmdJPcnnMFjFMcrVJhMF\n' +
      'wMRQMSQZHznRsqRbWp\n' +
      'ddgDDhfDrrDdjthHmdHrzpbVCVWFpfVqCWpWqpFs\n' +
      'hdvNdHtjMLJZvJwM\n' +
      'nWzZtWzHzZWgQHMNLDMDfDBfQbdD\n' +
      'MCPmRGGhqdmNjbDN\n' +
      'FRPlMlRChCvFggWZsHsZHn\n' +
      'ZGhhjdgwgcZHsPnRnSnbWscn\n' +
      'tltlfMQQQftDFJpMQJsWJWJsnWBnRSBbrBWP\n' +
      'lfLDpQMFMNfLjGjPPgZzwh\n' +
      'HcmvWcqnHLLPDzPPHM\n' +
      'MGGSfdJRdCglfrLjrjrLzLPzlF\n' +
      'CsgRgfwgdCwhsssJBBwvcnQnQNMvQtQm\n' +
      'nrVbwgnSTSgSnrZpjpWWqmWNHlqqpV\n' +
      'BcBPhSdsDlHNtNlJNP\n' +
      'RLFCQLQRRsBDDcRdGDddhCRDfwzvSCnzrbfrMfMgznwwfbZv\n' +
      'HJLzLNwBNzNJLzBJztRGzQVnDgwsjbgwssZwnDZbDQ\n' +
      'PhvlSvvPfMRlDbDsggbSjQSg\n' +
      'mFfhMlMrfchvPPpFTPvMvPzLBHWRHJNtzJGzzHpzBtCC\n' +
      'FLsgSLzLswdFgLBbWZnJDWHcmZnnBjHM\n' +
      'rpbrrqfqpvCbqqQQvvpClblRDHmjmmjJJZZnWMJmmJmmcRMc\n' +
      'qTppQvCfhzSVVTzbdL\n' +
      'ThTJtlqfDrDtffwqRCFCCnLwdnmpzRdF\n' +
      'WPQSSFsGMgQZWvFQgZgZQcCdmmzLMLCpNzCCddmLzdzm\n' +
      'cvVPGPQQGsZsgGPjVFccbHhThJHhDqfhDDjHqDrr\n' +
      'CgnCCnPMnMtGHDbMFQ\n' +
      'zLpwpRTwwRwhRchHwmqmGvvGbqmTmNQqvq\n' +
      'sHdhzlwrRVrdLzRrprrfjgfjVBnBCfSBZZgPfJ\n' +
      'SPMdWwWPrZwdrrWrSPLFDfgbQDfwDFfFglDQ\n' +
      'qLGBtGLpjzqmvQbvvpDvfFpR\n' +
      'jhLqqHBLGjtLqSZCssSTZZMshP\n' +
      'MhJCpPDpRRFRzQQNNqbcZjNZmVhjNm\n' +
      'LLSlLnGDmNqLbNjb\n' +
      'sfBngrBSTTSnSGHlTsHBGsBpFFdRdQPDCFPWRMzzdQWM\n' +
      'ZQtmgtWfPcgPgcsb\n' +
      'pvMhFThpHVTvPbcFcFJLJDsd\n' +
      'MTVHchVVHjHHTcpjMVBjjnQnGqQZnlqBmrWQQBffQQ\n' +
      'HfcRNJpJfhCmpGSqqGNjsjBnQl\n' +
      'tTdPwwtLTrrTVPSnQsbGPsnnlFllFQ\n' +
      'VvvTSTwWMrSZVwwrrmRmczJchHcHCZhRzD\n' +
      'wfRwhmLRnvrHqHhV\n' +
      'bJlBHlWlHMBPJzDlzMMJJSBlFnrGVrqspGGvpVGPVpGsVqvp\n' +
      'DWdStDMztCCHgZCtmZ\n' +
      'MHdsznVDDfcjcjDcdDjmMSCQwQpCpFCvqSZQqFzQpQ\n' +
      'lhJnLJJnTNrWTRqvqqPrFwZvwqQp\n' +
      'NghhtJBtnWLRTNjmcMDtjdsMfGDH\n' +
      'jgsvPffVmHfDqPSrNwnQwnwNhSvw\n' +
      'PZbGbCdcGdRCGtntQLQQLLwtpLNw\n' +
      'RbcPFBRFcdZBBJDBmTHjsD\n' +
      'dTTFJdzhmmmQpzVz\n' +
      'jtNLcctGGjtfrnVMsNQNQVVWnv\n' +
      'GcrcrfLtDggLftDFhZFdJFHJBVFBgZ\n' +
      'TTbqTgqCqZCrwmhQnnmrgh\n' +
      'MhpfsMLhfmrznLrQrF\n' +
      'RsStRMtjpHMfDtWsWsNDppsqlZqBlhNlbcNdTPClPqcvBP\n' +
      'lRhZPgnpRGZlSrmsLSvSzLVl\n' +
      'wwHdHCfDQCJHdwdDMdHCcDsLmNVvzVsWrcVNcVzLbrLz\n' +
      'dMCCwCtJdwDQJMtjhnvhpPhRZBhR\n' +
      'pBqMZfDffmBnvnNmPt\n' +
      'rhwLHCChrLPCMNWMCNmW\n' +
      'GSMVRSVwHLMRJDQJTZlJZR\n' +
      'sfstzPGRRBSngMfQLNNqgWLQLZZNgq\n' +
      'scVDjjjCDTVhHlDhHdvvjwjHrZmWQmJmrJJWqNqLJbrcQqZq\n' +
      'VvHlVHldTjvhpVplhVThhwjlPFSzPfGzpGBnsRffRRBPPGGF\n' +
      'WNFNfnWTSLSJTnWShTvVZCnvrdPrZvddVCrt\n' +
      'QwsMjppcpHCPdHsvPZ\n' +
      'lcwMGgpcGbzQpMgQwbDjDQZSJTRfShffWNJSSNFFbhSb\n' +
      'JDNgTgqDTggQbQGbZDWbJmVJrPVfPjlPfPwlljJC\n' +
      'FZzHFSznZZtptHzcSmCVrwfPVcwwVrCcdm\n' +
      'nMSStvnZFSHpLLtBtMzHnMWQvNhgDgGNRGNhgqRWTgqg\n' +
      'SJcrhvbBLBLrDpllvnwHQRnllHnQ\n' +
      'ffsjfMMZfVdCCgCfgTzmzslRtwFwFtTnqqHTJRQnqRqq\n' +
      'CVPgmdggVjCJSrhrbrPrrSLW\n' +
      'LPtcLtgddLMRRCMRpTBRrZnppvvGRvBw\n' +
      'WNNJjDjqSjJSqWqzNqzlSlBTGGFvrppSrwTFpn\n' +
      'qbNDWNNHbJqVtctwVmsfLCLP\n' +
      'FvSSLMqgvVSQjQfgwpwWpj\n' +
      'BthszRPRRNbNtzmHRbHNRNPfwJGcsswWQpffJpfsJcQFwJ\n' +
      'bBtzPmRrbBRHtNCzPhqdCLFMLSSvdnvCTnML\n' +
      'VPHWJPDjVLDDjDSFDJhgdnNGdbblzTzNjlnNbl\n' +
      'ZprsRZMQwwmGZsvtQZgTfggqnbfdTzrbqlTd\n' +
      'GZMtsscmsRZswwBQHBhDDJJPPCPWSWCJ\n' +
      'mNDNNmmVMSVgGgGGqsqGLhQqsLGhLq\n' +
      'nZBTZpJPhCpnnrsqbbcfczJfFccz\n' +
      'HpBZZRPRHjnPPjrHnRtCZnBdShDVlMDNDgVmtmDdVDWSdN\n' +
      'tBftztmztGBBCBSGHBmhvHHcchbshhThpbLJHJ\n' +
      'wwzMrrMnQdldVdMvJTcLNnphphbLJv\n' +
      'ZzwPVrWQlwrdStGGCWqDSSGW\n' +
      'QwfrQPvhwPfzQrvWWpQpvVGGTDGsjbgNNcbfsGTsDFgG\n' +
      'CtddSdZMRRdnJhRnHtZtlRMbGGDjDgggjNTZDNgTGFgGjc\n' +
      'mdmdCnHhVWmLmwwL\n' +
      'zLcWSWFcPJLWrWLSZrJLjVjHtjVsrdtstHdtVQgg\n' +
      'nChlwwnmhlCNqhhjHMgDjVVdwMjdtd\n' +
      'CNnBmNNThhhdhCdlBGGlGvNpcJbJLSbcZzcFJzpJTWPbzc\n' +
      'LdPZTPVpLCVTtCNsNsfFnlDC\n' +
      'SMwqcqcWQMbMhWQzBnsNfsFwrnnNNlrs\n' +
      'WMMWhvQRNNNjvLgZ\n' +
      'DWFGzrtfsZHZZMLt\n' +
      'pNwNzNCNTpppmnvNMTLVjHLBLLjMRTLH\n' +
      'PPdlPmJJNNClDdcdDDfWhzrW\n' +
      'nSJVSHQQnwLThnhrML\n' +
      'ddsjfRdGZjmGjRTwwTZhwrMwWwtb\n' +
      'qCdfRdMmgssPfjsdjdPspBzQpScSSCBpzNBQzcQz\n' +
      'fJnmRMJrlrmRmTRmbqssWVdqNVQdswdNNb\n' +
      'GZggFHGhHHgHSFvtHPPPsfwgwNsVqjqNpNjNNssN\n' +
      'PPSPDDBPBmBMlLfmLr\n' +
      'BdqdCBqqCVPVTZBrlJcTcTJTcfcbwwmcgv\n' +
      'WjGGLzLMhpWQmRGhpHfbhcDhHHHhgcsbJD\n' +
      'tQzSGjWRzWBntntrZmVB\n' +
      'clfLQLgfzfTLDMwNrNrrNDGCGG\n' +
      'tmbpFtBvvmvdQQdFQwMJCG\n' +
      'SnbtnqnSbnQQsBqzgLgVsLZTLTPfVg\n' +
      'QnQBQQBVzqqzpmfgBpnqSDFPjhhWsFVhlsFFsDstFs\n' +
      'MGGrTHcvRTTrrrCDpjvWtFPlFlsvjp\n' +
      'bZbpTpJJBBQmBmJf\n' +
      'dNVgDdVtPcNPhgTLPLpTPlnTHHRn\n' +
      'WrvjvwjWwfwWjGJsrwBjQJjTQLbnSTTmpTRQSTClHTbLmn\n' +
      'JqWWGvBJBwGJfJJGvwqZZddFtDFhgDqZhHNM\n' +
      'VwJcNgbfvfJbfcmGLZfPhZLfZGTDhP\n' +
      'CnnrlBlprsBnzQFntnZLqDhZZqThWGtWWSPL\n' +
      'FllFdCjzlsCzjJNJGGJwHHVg\n' +
      'fTbVBmNJCJRVbTmbfJFHsDjQHDHQjnQRsvDn\n' +
      'cLWcrGtttddMPhrPhPtPrtzsnSQQBvHjFpFSpDHsMjnvjD\n' +
      'PrPgPdhGWLrrqgdqcVCffbNblBwfVmwqwC\n' +
      'gmBfbmlbBDqrdfrDcJ\n' +
      'PwVWrQphQWWhQsJFcMPqzDdcJq\n' +
      'QWCSSHpSQWCttQpCRCHNSlZBtrmBZTjvGgZjmBZjBn\n' +
      'JrnhMPvtVtPVHJGrBrQwTmQmRGGB\n' +
      'pSSZCFClCbbSLbljZlSlFFszzBwcZNwTzQNDmBwGTBNTBz\n' +
      'ldsCCjpFjCqdLgsFjpsLFQgtnfqtJvnMtnvhWnHHMnnVWV\n' +
      'hzNHzHjWNzwHjjhprpGvGgvGvvpv\n' +
      'PLBVVRPDLdrgCdMrdrdC\n' +
      'FmBTqTmLPrsFqTBDcTTVtNNJztqWQNQtWWtJqNNz\n' +
      'fFffFvFBgHQWHdvfGglBWbqbPSSbSwVntPhZwwbS\n' +
      'jJCMzNMCjNCLNMjjphPSPqhbqnwPZLSqZh\n' +
      'rNpJJDzpcNMzzdBnGcQTccBvgv\n' +
      'FRFMwsrzVtwstgbCHHJJPgNb\n' +
      'hfZGhZDnnTTHTCCNzJjH\n' +
      'hppDvznmZphZQVFQwFVWlRqFls\n' +
      'jrjrgdHdFBZsBlcCGghWNgpgbCCp\n' +
      'QwJJqQQMLwPTwLMMwzvzwwzhCWbvcNcCChWpchWbNGfFff\n' +
      'qqFQJTmwJSPjZsrlnBjdHm\n' +
      'QfffRppWfHpQSrWVpSGmGMMccSjBjmmGmc\n' +
      'qdzLvbwzwdsWwnFdBBcBhMjMDvBBcBhc\n' +
      'bPdZPqddqzFsZVRptZZQHVWNpN\n' +
      'BzBQQHNjTSzzJDDFZFgJDJ\n' +
      'qLvCnLpfCpqCnLJhntRglFncDrGrllmZFZlDrc\n' +
      'JpqvfhRhLddfpbbtsdJWjHSwHHTNSQNPTVHQTb\n' +
      'qVQCCVlQZWgHZMqgqWlrtScFwrmtmcJqSSsSJS\n' +
      'MzdnddpNLzhRpzbzNPPBbPScjcnmrwSFjSjSJFtrwjcF\n' +
      'ddTzRMPLdLbvhBRdLWGQClVVCWQZQDTGGf\n' +
      'DHHTsldDNdPnVDCRDCNHllHwcMpprSMpRmphhRWhrhmzSS\n' +
      'qJLBqQLvJLQgftgPjJrhrMMWSmWMmMrrSqrc\n' +
      'FjfFftgLBjJPBLQZGvvZtNClnTTNGCdHTbCCNsnslH\n' +
      'jHHNsNqhjsShsshdRRCDMfMbCWHBrGGC\n' +
      'TJQFmnpgmTpBDCgCMCDZCGDC\n' +
      'FwpQzwQTmVvwTJmFJzTcQSdhBNztNPNjSlqLhBNhSh\n' +
      'vBCfSDcRMfRcRHSRRZZtPwrWWNtdSmrNVGSdwm\n' +
      'gbLnTzqTbjhGqFzgWrtttQtrPQTtNPmP\n' +
      'zbhjzglgzzlBGcsflsCl\n' +
      'jNHDNNHjVGVDNQFDTQSFZzDQTd\n' +
      'vvLwhbnpvPPgClwnfFTmTZQgffFFtTfc\n' +
      'LrhrLvwrnJvhCHVVRZNMjsRJVB\n' +
      'ShfcBWfvdhhJBBVwCJjHTRNwRVNC\n' +
      'qQzlDqMDDDslPqGVLTNZVpPwTRZZpV\n' +
      'bgbDbsqzsDTcfrgFFdgg\n' +
      'vlRHvvHwvMMMTTlvjmRtBjSJmSnDnpdrpSSrJJnDQrLp\n' +
      'cPfCgZZzNzzcGhNszcTPNZLrnVSJpJhDrrhSSQSpDDQn\n' +
      'FbTgbGcgNgcFbPFHMqvjjRtjRWvFvt\n' +
      'fZTnqfFFDNglcjdjZcfLGQJBwrGGQwbGQTBBJz\n' +
      'VhvfvsPpWRChmphvRGBbBLGhSbLrBQBSwb\n' +
      'pCsCsHvsstPsfRMMMtmDqFjngdFZqDHFnNFFjl\n' +
      'PVVwffMlfGWMDDSwfDwVpRpsZRjBHgpSsjJSpBSp\n' +
      'TdnFbqTFdmbjctcqcbRBZtJJZgsBzBBzvgHJ\n' +
      'bNmbcqnnbNFLChCVCfjDfWlMjVDPCr\n' +
      'JBLLjBQccLLJhcBDDlSrdFDsVhrVsR\n' +
      'HgNWCgqWGbvCRRZvGWvZmszsSlrWdSdFrWzSldDF\n' +
      'qvGCZGHggRNHvGTgvLnBjpjjPJwTPjLcJj\n' +
      'GCGwQrwBZMZdGVdLzbqbbp\n' +
      'TRfTTCtgcDmhtDmsTDVSbvpLdNpzNVRqVdVL\n' +
      'CfDJjscgTcsjfhtFZljPZWZMWPlZjQ\n' +
      'WsrjjfRfjjZjwjWjBpDpVpVhMBsMMSBT\n' +
      'JgmqHnCHHPCCtCJgSZMgZppDTgzvzZMz\n' +
      'HCGCGqqqCtmnHnqLFHWjlFrWRRbfjZccNWrR\n' +
      'BJBfSfPLPvdhvrbbvpDsHgDTzgpdzgZpgN\n' +
      'cVcmRnCWCqGngHpZsZsTsqNN\n' +
      'jmGCVwWjjnWFMjGwcwmrLJbBJPbLSrPPTbFBTr\n' +
      'SPZmmtlmqjZlZMwhlrtggqGGcCLCpfGLgqdCqF\n' +
      'FBBVDVTVDJfgcddLCDdp\n' +
      'zzVHvVNTbWJJTTRbVWBFJbWHmwmSPlMjPSShjlhMhhrrml\n' +
      'GJZJZTsnhsDJtVZdtsZJZrBCQpLjQgBnrQgjCjQQQj\n' +
      'RPSfqcRShHbFcPSfBqLLprBCwrQQQCqg\n' +
      'zPzPRHbFPcRRRHPclMhSfvfZsJZVTTZsJNVMGWGVdGTWWD\n' +
      'lCZrCLWCwVllGzWPPBMTFpsbGdsTpsbNMgFb\n' +
      'RDjtjHcHjcHctDRtjnhtnHTgMqTMqhTbdbdZbgFqZdMN\n' +
      'vfDmvfjtmvtcHmjZfSRZHQzBLrVLCJLJLfJBPzVJlwPw\n' +
      'JMTHVZMWNSCwCwMS\n' +
      'nsddQbDCnQQdDBPdCQCSvwpDvwffhfSvpmppvp\n' +
      'BssqBFtqRHgTqVRC\n' +
      'cWTTthtrgrzpCdCddtpz\n' +
      'SSSLNJLGLSLfCJfJFQCJzQ\n' +
      'swMPMZVMMSlMSZMqVSSHznzcqgzWTHgTnhbnrr\n' +
      'RJjjgMjWShPqchtbVBPV\n' +
      'DDddwCnZMHLLvDnfLrvvbVbbBtpwVBVPwtVpbcbb\n' +
      'zrvnvLrlZCHrfZZLffHZHHTsTmsQgFQSFTMjjQlFTRmR\n' +
      'zhTTMLRVTzLbVqwVRJgDQQsSCgCDNgsZCpqp\n' +
      'rrmrBmmWrWnHjWnGWrnGnhDHSQgNSpQsCgSNgtNtDDHZ\n' +
      'fBrGPGmGPBcTMfLhJVTc\n' +
      'TbTCjTBSbCncHsDZDZPhZbzv\n' +
      'rMwplFdlWWJMJzhhpGtHtvHSSP\n' +
      'fMMfwWdWrNfJNdlVgMcTLTmLffjTqnLScCjL\n' +
      'SwhTllwJDwqqBWLBbNtfhjBB\n' +
      'mvllZMmRMZGFZRfctLWtWttzfNLR\n' +
      'MGvHMCGpVnFGlgvVFFnpnGmmsHrDJJdSsqPqJSqDJJdTTDqD\n' +
      'QTTcqJZJhHSpShhFpFzjDDwwsFzpdg\n' +
      'NBMnBvmBPvwrqvgvvqgD\n' +
      'bNNGmWmbbClQTQRqchhQbf';

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  it('test TestInputPuzzleOne', () => {
    const testInputArray: string[] = puzzleOneTestInput.split('\n');
    expect(service.findItemsThatAppearInBothCompartmentsAndCalculatePriority(testInputArray)).toBe(157);
  });

  it('test Real InputPuzzleOne', () => {
    const realInputArray: string[] = puzzleOneRealInput.split('\n');
    expect(service.findItemsThatAppearInBothCompartmentsAndCalculatePriority(realInputArray)).toBe(7716);
  });

  it('test TestInputPuzzleTwo', () => {
    const inputArray: string[] = puzzleTwoTestInput.split('\n');
    expect(service.findBatchesAndCalculatePriority(inputArray)).toBe(70);
  });

  it('test RealInputPuzzleTwo', () => {
    const inputArray: string[] = puzzleTwoRealInput.split('\n');
    expect(service.findBatchesAndCalculatePriority(inputArray)).toBe(2973);
  });

  it('test charToNumber', () => {
    expect(service.transformCharToNumber('a')).toBe(1);
    expect(service.transformCharToNumber('z')).toBe(26);
    expect(service.transformCharToNumber('A')).toBe(27);
    expect(service.transformCharToNumber('Z')).toBe(52);
  });
});
